### ISSUE TITLE
Can't attach rope?

### ISSUE THREAD

**Issue by rdwulfe** [SteamPunkNation/CreateHorsePower#2]
Nothing I've done allows me to attach a rope to the horse crank. I've followed the ponder, which mentions that allowed surfaces are in the config file. I cannot find a config file in ./minecraft/config for this mod, either. Uninstalling this mod until these issues are fixed.

**Comment by SteamPunkNation** [comment]
Hi there, in order to attach the rope (lead) to the horse crank you must have another lead in your hand (You need two total, one to attach to the mob and one to activate the block). The config file is a server-side one so you can find it in your world's serverconfig folder named "createhorsepower-server.toml" to see all valid blocks and mobs.

Hope this helps!
-Steam

**Comment by ElRichiRicon** [comment]
I was about to report this issue again.

Needing two leads shouldn't be a feature. Attaching to a fence can be done with a single lead.
It is also not explained anywhere in-game.

**Comment by Pyritie** [comment]
I'm getting a few reports that this is still an issue in 1.1.

**Comment by Dottoraqn** [comment]
Yeah, I spent like an hour trying to figure out why I couldn't hook the horse to the crank. If the two leads thing is too hard to fix, could it be mentioned in the ponder that you need 2? This is a really fun, cute mod and my horse blacksmith setpiece looks great in the town I'm building, so thank you for the mod!
